# Generated by Django 3.0.2 on 2020-01-22 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extend_user',
            name='profile_photo',
            field=models.ImageField(default='default.png', upload_to='profile_photos'),
        ),
    ]
