# Generated by Django 3.0.2 on 2020-01-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_auto_20200122_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extend_user',
            name='wallet_balance',
            field=models.FloatField(default=0.0),
        ),
    ]
